name: Build and deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: nfp_FRLCaBMEbo82yRvbYFZNTdKvks3d61E8d1cc
          NETLIFY_SITE_ID: 24b095fd-3dca-4ad0-8e72-efffb40249c0
        run: npx netlify deploy --auth="$NETLIFY_AUTH_TOKEN" --site="$NETLIFY_SITE_ID" --prod --dir=dist
